### ISSUE TITLE
All functions directly present instead of single button

### ISSUE THREAD

**Issue by ARAWKMK** [haydenull/logseq-plugin-git#1]
Hi,
I was trying your git plugin and saw that instead of single git icon, shown in your demo image, 

![image](https://user-images.githubusercontent.com/81613544/168796826-2f96a980-b4c4-4c1c-95e6-95ba3c4b0f8c.png)

directly all the options are displayed which really clutters the logseq ui

 ![image](https://user-images.githubusercontent.com/81613544/168796383-3ab74fce-4d51-452f-a8d4-1d33eab652f4.png).

**Comment by CharlesChiuGit** [comment]
I have similar issues. Seems like the author use the mac layout which is incompatible with windows layout.

**Comment by haydenull** [comment]
Sorry that Windows has not been tested since the release, version 1.0.2 should fix this issue.

**Comment by CharlesChiuGit** [comment]
@haydenull The new version does fix it! Thanks!

**Comment by haydenull** [comment]
Currently, it can only be closed by clicking a button in popup, such as show log.

**Comment by CharlesChiuGit** [comment]
Cool! Noted.

**Comment by ARAWKMK** [comment]
Multiple buttons insted of single icon issue is resolved. But still facing same issue as faced by @CharlesChiuGit that the pop-out pane won't collapse no matter where I click. Other plugins icons have this feature. As you informed we can click on any button and it does that work and collapses the pop-out pane.

Windows 10, Logseq v0.7.0, logseq-git-plugin v1.1.0

**Comment by haydenull** [comment]
> In case somebody else has this issue: I was having the same issue as @CharlesChiuGit with the newest version of your plugin, but with the older Logseq v0.6.6.
> 
> Updating logseq to v.0.6.9 fixed the issue and now it works great.
> 
> Thanks a lot @haydenull !

Yes, logseq has modified the html structure of header in the new version.
