### ISSUE TITLE
有时候点击按钮不会弹出菜单

### ISSUE THREAD

**Issue by rebron1900** [haydenull/logseq-plugin-git#10]
如题，需要重载插件才能正常淡出操作菜单。

**Comment by haydenull** [comment]
请问下你用的 logseq 和插件版本是多少呢，以及电脑操作系统的版本。

我这边看一下能不能复现

**Comment by lef-est** [comment]
我也有遇到 插件是市场最新版本 logseq 0.7.5 Windows 10

**Comment by rebron1900** [comment]
logseq version 0.7.5
System OS: Windows 功能体验包 1000.22000.778.0
---
不知道能不能有快捷键来commit，push呢？
比如，`ctrl+a`为commit，`ctrl+shift+a`，为push

**Comment by zhaobenx** [comment]
+1 mac 系统 logseq 0.8.4， 插件 1.4.0

第一次安装后没菜单，看见这个 issue 后 reload 了一下才有

**Comment by likayo** [comment]
+1 Windows logseq 0.8.8 插件 1.4.0

Reload 之后也没有修复

**Comment by Esther-99** [comment]
+1 Windows11 logseq 0.10.1 插件1.5.4
打开应用时也不能pull其他地方的更改
