### ISSUE TITLE
The current repository is not synchronized with the remote repository, please check.

### ISSUE THREAD

**Issue by xiaotong-sun** [haydenull/logseq-plugin-git#15]
I always receive this warning "The current repository is not synchronized with the remote repository, please check"  when using this plugin. But I do have a remote repository already, I don't know why it warns.
![image](https://user-images.githubusercontent.com/58971249/186062364-92250205-8b14-438f-84c6-6ce409b0ccfb.png)
What should I do to solve it?

**Comment by haydenull** [comment]
Version 1.4.0 added a switch to automatically check the synchronization, you can upgrade and try again.

<img width="995" alt="image" src="https://user-images.githubusercontent.com/17695989/186089278-65302791-3428-4502-b717-41f8b895f146.png">

**Comment by xiaotong-sun** [comment]
Thank you very much! The problem has been solved.
