### ISSUE TITLE
Auto push is too frequent.

### ISSUE THREAD

**Issue by jin8495** [haydenull/logseq-plugin-git#16]
Hi. I am using your plugin very well.
Built-in git lacks features, but this is not.

I am using multiple devices across Win11, macOS, and Android.
So the auto push is essential for me.

However, the current way of pushing is too frequent.
For example, it pushes the commit whenever I swipe out the desktop to see the other material while I am writing notes.
It kinda makes too much log which I don't want.

So I am suggesting that considering both hiding and duration.
If the Logseq is hidden and the duration is shorter than the user had set, it doesn't push.

I appreciate your hard work.
Thank you again.

**Comment by k2s** [comment]
this is addressed in https://github.com/haydenull/logseq-plugin-git/pull/39

- currently there is no real auto-push functionality
- but for you `Ctrl+S` or `Sync` action from menu should work well
