### ISSUE TITLE
button style issues 

### ISSUE THREAD

**Issue by sven-dibowski** [haydenull/logseq-plugin-git#20]
The style of the buttons look a bit off and don't look the same like on the repo screenshot. Maybe that's a Linux only problem? The problem is independent from any theme of logseq.

![image](https://user-images.githubusercontent.com/30394136/196962718-f695019e-1822-4809-9fb9-0c6e94c5b232.png)

OS: popOS 22.04

**Comment by douglarek** [comment]
I have this issue to. Maybe the backgroud should be none and follow the current theme.

**Comment by haydenull** [comment]
Version 1.4.1 fixes this problem, you can try again.
