### ISSUE TITLE
Git push failed (linux)

### ISSUE THREAD

**Issue by celsomiranda** [haydenull/logseq-plugin-git#21]
When committing and pushing I get the following error:

> Git push failed
> ssh_askpass: exec(/usr/libexec/ssh-askpass): No such file or directory
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

I'm pushing to a private repo, authenticated via SSH. If I pop to the console and do a manual `git push` it pushes the commits no problem.

**Comment by breadchris** [comment]
@celsomiranda there isn't much that this plugin is going to be able to do. I have run into this before when using Obsidian and I needed to my ssh key to the agent on startup in order to get it working.

**Comment by celsomiranda** [comment]
But my ssh key IS added to the agent...

It doesn't even require me to put in my password again when I do a `git push` on the console right after logseq fails to do it.

**Comment by celsomiranda** [comment]
Nevermind.
Problem was related with it being a Flatpak.
AppImage works as intended.

**Comment by grissu** [comment]
Alternatively you might want to change the "Secure Shell agent" setting of the Flatpak with Flatseal.

**Comment by Karrq** [comment]
I don't have askpass by choice, as I use KDE Plasma so I have `ksshaskpass`. Is there a way to specify what executable to use?
