### ISSUE TITLE
Cannot work with the remote repo: permission denied

### ISSUE THREAD

**Issue by xodmqjw** [haydenull/logseq-plugin-git#24]
I'm trying to work with my Logseq vault with this plugin. However, when trying to push changes (or pull) to GitHub I'm getting this error:
```
Git push failed
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Looks like the plugin just does not "see" that I have permissions. Because when I'm working with the vault using terminal - it works:
```
$ cd MyVaultDir

$ ssh -T git@github.com           
Hi xodmqjw! You've successfully authenticated, but GitHub does not provide shell access.

$ git push -v            
Pushing to github.com:xodmqjw/***.git
To github.com:xodmqjw/***.git
 = [up to date]      main -> main
updating local tracking ref 'refs/remotes/origin/main'
Everything up-to-date
```

I've already tried to re-install Logseq, plugin, re-clone the vault - still get the error.

OS: Fedora 36
Logseq: v0.8.11
Git Plugin: v1.4.2

**Comment by FreshPhilosopher** [comment]
Did you install logseq via flatpack? I uninstalled it and had no problems with the AppImage. It's probably some problem with SSH agents and their environment variables or a wrong path/config for ssh-askpass. But I don't know. The problem also occurs without the plugin. Vscode has a similar issue since 2018!

**Comment by xodmqjw** [comment]
Thanks, this helped! I allowed access to ssh agent via Flatseal and all works now.

**Comment by ohare93** [comment]
Same issue for me on windows. I can authenticate via ssh in every command line I have available, yet Logseq cannot. No idea what to do.
