### ISSUE TITLE
Not working with logseq 0.9.9 - cannot find 

### ISSUE THREAD

**Issue by fl-la** [haydenull/logseq-plugin-git#33]
Hi,
it seems that the plugin does not work with logseq 0.9.9.
If I want to push I get this error message:
`/tmp/.mount_LogseqO6virV/resources/app/node_modules/dugite/git/bin/git: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.32' not found (required by /tmp/.mount_LogseqO6virV/resources/app/node_modules/dugite/git/bin/git)`

cd to this directory and trying to manually this git version confirms this. How is the git version specified? Any suggestions about how to solve this problem?

**Comment by Nixew** [comment]
I'm having the same issue. Apparently it does find libc6, but its version is 2.31 on Ubuntu 20.04. Ubuntu 22.04 has libc6 version 2.35. Why does the plugin want any of those three specific versions 2.32 - 2.34?

**Comment by k2s** [comment]
> I'm having the same issue. Apparently it does find libc6, but its version is 2.31 on Ubuntu 20.04. Ubuntu 22.04 has libc6 version 2.35. Why does the plugin want any of those three specific versions 2.32 - 2.34?

This plugin doesn't require anything else then Logseq API. This plugin has no direct access to binaries on your PC. It uses `logseq.Git.execCommand()` to perform Git actions.
Probably you would run into the same problem if you enable `Settings/Versioning`, which is Logseq native functionality.

Maybe this will help https://github.com/logseq/logseq/issues/1643 ?

**Comment by fl-la** [comment]
I checked it with the most recent version 0.9.14 of logseq. The problem still exists. Once I activate the native functionality I can use the plugin, too. Does the plugin requires to have the native git functionality of logseq be activated?
