### ISSUE TITLE
Plugin seems not to work with Logseq 0.10.2

### ISSUE THREAD

**Issue by tangit86** [haydenull/logseq-plugin-git#48]
Just updated Logseq to [v0.10.2](https://github.com/logseq/logseq/releases/tag/0.10.2) (Ubuntu - Logseq-linux-x64-0.10.2.appimage) and:
- plugin fails to render menu items (buttons) and doesn't catch changes and/or impossible to commit/push
- no errors in the console

Uninstalled, restarted Logseq, re-installed and still non functional.

Switched back to [v.0.9.19](https://github.com/logseq/logseq/releases/tag/0.9.19) version of Logseq and it functions as expected again.

**Comment by andzejsp** [comment]
0.10.2 not working, 0.10.1 works for me. Windows 10.

**Comment by DawMatt** [comment]
The Developer Tools console contains the following message when the plugin is enabled in 0.10.2:

```
index-c9525fa1.js:145 Uncaught (in promise) Error: Not existed method #git_execCommand
    at br.R (lsplugin.core.js:2:49378)
    at br.<anonymous> (lsplugin.core.js:2:93271)
    at a.emit (lsplugin.core.js:2:28521)
    at X.<anonymous> (lsplugin.core.js:2:88623)
    at lsplugin.core.js:2:53506
    at Array.forEach (<anonymous>)
    at X.listener (lsplugin.core.js:2:53491)
    at g (helpers.js:151:57)
```

It is also worth noting that the inbuilt Logseq auto-commit functionality doesn't seem to be working in 0.10.2. I rolled back to 0.10.1 and the Git functionality is working again.

This "Plugin API" enhancement may be a factor? https://github.com/logseq/logseq/pull/10399

**Comment by ssilb4** [comment]
@DawMatt @andzejsp Thank you!!!! I am using logseq with git at first. but It doesn't work. It is because of 0.10.2. You save my 7 hours.

**Comment by kadd13** [comment]
same . windows 11, logseq 10.2 . Last commit from the author of this plugin was 5 month ago. Maybe some alternatives, except 101 ?

**Comment by kadd13** [comment]
> same . windows 11, logseq 10.2 . Last commit from the author of this plugin was 5 month ago. Maybe some alternatives, except 101 ?

even 10.3 version. When i press ctrl+S - red bot brgins to blink, but nothing happens

**Comment by philipmorg** [comment]
> When i press ctrl+S - red bot brgins to blink, but nothing happens

Same here; Logseq 0.10.3 on Windows 11

**Comment by Chanstien** [comment]
Same issue; Logseq 0.10.3; Win 10

**Comment by tibitTW** [comment]
Same here; Logseq 0.10.3; macOS Sonoma 14.2.1（23C71）

**Comment by xyhp915** [comment]
A quick patch PR for the latest Logseq release #50

**Comment by andzejsp** [comment]
confirming, it works on 0.10.3 windows 10, thank you
