### ISSUE TITLE
Popup not showing.

### ISSUE THREAD

**Issue by benwmx** [haydenull/logseq-plugin-git#52]
In the latest version (v1.5.5) after the update, the popup window will not show when the button is clicked.
![Peek 2023-11-28 17-39()](https://github.com/haydenull/logseq-plugin-git/assets/60202444/39159106-8397-4bc3-a3d1-d884cba41d1c)

this is what console shows : 
![Peek 2023-12-29 17-18](https://github.com/haydenull/logseq-plugin-git/assets/60202444/ee8dd76a-85d2-4fab-9b86-d2c7ed12b0dc)

**Comment by GOWxx** [comment]
Same error.

logseq version: 0.10.1
git plugin version: 1.5.5

![image](https://github.com/haydenull/logseq-plugin-git/assets/12870715/e1305e9c-b95d-4d35-a4c0-0f7b42a2cd53)

**Comment by GOWxx** [comment]
> Same error. 同样的错误。

These two versions work fine.

logseq verson: 0.10.3
git plugin version: 1.5.5

**Comment by haydenull** [comment]
The latest version of Logseq （0.10.3） has made some changes, and 1.5.5 is released to adapt to the new version.

If you are using an older version of logseq, you can download the old version plugins in the release.

**Comment by benwmx** [comment]
@haydenull Yes that's true, the issue is not present in the latest version of logseq v0.10.3
