### ISSUE TITLE
Update v1.5.5 bricks plugin

### ISSUE THREAD

**Issue by AshesITR** [haydenull/logseq-plugin-git#53]
Thanks for the awesome integration so far!

I've updated to v1.5.5 from the previous version, but that has unfortunately completely broken the plugin for me.
I tried uninstalling and reinstalling to no avail.

Here is the error message that is shown to me:

```
-C error: Error: Git could not be found at the expected path: '/opt/logseq-desktop/resources/app.asar.unpacked/node_modules/dugite/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
```

Apparently the directory "dugite" doesn't even exist at the path from the error message:

```
➜  ~ ls -l /opt/logseq-desktop/resources/app.asar.unpacked/node_modules/
total 12
drwxr-xr-x 4 root root 4096 26. Dec 01:51 better-sqlite3
drwxr-xr-x 4 root root 4096 26. Dec 01:51 electron-deeplink
drwxr-xr-x 3 root root 4096 26. Dec 01:51 @logseq
```

Do you have any advice on how to cleanly remove the old version and then reinstall the plugin so things go back to normal?

**Comment by haydenull** [comment]
May I ask which version of Logseq you are using?

Version 1.5.5 is designed to be compatible with logseq 0.10.3.

**Comment by AshesITR** [comment]
Thanks for the hint and sorry for not checking myself.
I was indeed on 0.10.2. Updating logseq to 0.10.3 fixed the issue.
