### ISSUE TITLE
Git push failing on logsec mac git extension, but in terminal works. error "Device not configured"

### ISSUE THREAD

**Issue by shermanchris24** [haydenull/logseq-plugin-git#58]
Pushing through terminal works fine but getting this error when commit pushing though logseq git extension on mac.

commit success, then ->
error message. `Git push failed
fatal: could not read Username for 'https://github.com': Device not configured`

**Comment by amanintech** [comment]
I have tried authentication using SSH as well. Still the same issue.

**Comment by amanintech** [comment]
I used this command and it fixed it `git config --global credential.helper store`

**Comment by shermanchris24** [comment]
Thank's I tried that and it didnt work for me. Although I believe I was using https.

I switched to ssh and created a new key and linked it to github and is working now, thanks

**Comment by shermanchris24** [comment]
Thank's I tried that and it didnt work for me. Although I believe I was using https.

I switched to ssh and created a new key and linked it to github and is working now, thanks

**Comment by Muzych** [comment]
> Thank's I tried that and it didnt work for me. Although I believe I was using https.
> 
> I switched to ssh and created a new key and linked it to github and is working now, thanks

yes, seems like it's just support ssh way , I switched to ssh and is working for me too.
